"""yes

Revision ID: a62a00c64502
Revises: 
Create Date: 2020-09-19 21:05:06.197735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62a00c64502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_desc'), 'products', ['desc'], unique=True)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_img', sa.String(length=128), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_name', sa.String(length=64), nullable=True),
    sa.Column('order_desc', sa.String(length=128), nullable=True),
    sa.Column('time_ordered', sa.String(length=32), nullable=True),
    sa.Column('order_flag', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_desc'), 'orders', ['order_desc'], unique=False)
    op.create_index(op.f('ix_orders_order_flag'), 'orders', ['order_flag'], unique=False)
    op.create_index(op.f('ix_orders_order_name'), 'orders', ['order_name'], unique=False)
    op.create_index(op.f('ix_orders_time_ordered'), 'orders', ['time_ordered'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_time_ordered'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_flag'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_desc'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_desc'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
