"""removed unique price

Revision ID: e9a270a46e97
Revises: 49f2035d1070
Create Date: 2020-05-14 15:31:40.892022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a270a46e97'
down_revision = '49f2035d1070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_price', table_name='products')
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.create_index('ix_products_price', 'products', ['price'], unique=1)
    # ### end Alembic commands ###
