"""added email verification

Revision ID: ec5fe60db468
Revises: a4f4a4404570
Create Date: 2020-09-19 20:25:47.591617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5fe60db468'
down_revision = 'a4f4a4404570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isVerified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isVerified')
    # ### end Alembic commands ###
