"""okay

Revision ID: f5540d326ce3
Revises: f6b2078b6c7f
Create Date: 2020-05-19 22:49:16.674821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5540d326ce3'
down_revision = 'f6b2078b6c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_order_desc', table_name='orders')
    op.create_index(op.f('ix_orders_order_desc'), 'orders', ['order_desc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_desc'), table_name='orders')
    op.create_index('ix_orders_order_desc', 'orders', ['order_desc'], unique=1)
    # ### end Alembic commands ###
