"""added orders table

Revision ID: f6b2078b6c7f
Revises: e9a270a46e97
Create Date: 2020-05-15 19:13:21.488662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b2078b6c7f'
down_revision = 'e9a270a46e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_name', sa.String(length=64), nullable=True),
    sa.Column('order_desc', sa.String(length=128), nullable=True),
    sa.Column('time_ordered', sa.DateTime(), nullable=True),
    sa.Column('order_flag', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_desc'), 'orders', ['order_desc'], unique=True)
    op.create_index(op.f('ix_orders_order_flag'), 'orders', ['order_flag'], unique=False)
    op.create_index(op.f('ix_orders_order_name'), 'orders', ['order_name'], unique=False)
    op.create_index(op.f('ix_orders_time_ordered'), 'orders', ['time_ordered'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_time_ordered'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_flag'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_desc'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
